api_platform:
    # The title of the API.
    title: '%env(APP_TITLE)%'

    # The description of the API.
    description: '%env(APP_DESCRIPTION)%'

    # The version of the API.
    version: '%env(APP_VERSION)%'

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    # Enable the FOSUserBundle integration.
    enable_fos_user: true

    # The list of enabled formats. The first one will be the default.
    formats:
            json:
                mime_types: ['application/json']
            jsonld:
                mime_types: ['application/ld+json']
            xml:
                mime_types: ['application/xml', 'text/xml']
            html:
                mime_types: ['text/html']

    # Enable the Swagger documentation and export.
    enable_swagger: true

    # Enable Swagger ui.
    enable_swagger_ui: true

    collection:
        pagination:
            client_items_per_page: true
            items_per_page_parameter_name: limit