services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    ### Modify swagger documentation
    app.swagger.article.boolean_filter:
        class: App\Swagger\Filter\SwaggerBooleanFilter
        decorates: 'app.article.boolean_filter'
        arguments: [ '@app.swagger.article.boolean_filter.inner' ]

    app.swagger.article.search_filter:
        class: App\Swagger\Filter\SwaggerSearchFilter
        decorates: 'app.article.search_filter'
        arguments: [ '@app.swagger.article.search_filter.inner' ]

    app.swagger.article.group_filter:
        class: App\Swagger\Filter\SwaggerGroupFilter
        decorates: 'app.article.group_filter'
        arguments: [ '@app.swagger.article.group_filter.inner' ]

    app.swagger.user.group_filter:
        class: App\Swagger\Filter\SwaggerGroupFilter
        decorates: 'app.user.group_filter'
        arguments: [ '@app.swagger.user.group_filter.inner' ]

    app.swagger.tag.search_filter:
        class: App\Swagger\Filter\SwaggerSearchFilter
        decorates: 'app.tag.search_filter'
        arguments: [ '@app.swagger.tag.search_filter.inner' ]

    app.swagger.category.search_filter:
        class: App\Swagger\Filter\SwaggerSearchFilter
        decorates: 'app.category.search_filter'
        arguments: [ '@app.swagger.category.search_filter.inner' ]

    app.swagger.project.group_filter:
        class: App\Swagger\Filter\SwaggerGroupFilter
        decorates: 'app.project.group_filter'
        arguments: [ '@app.swagger.project.group_filter.inner' ]

    app.swagger.comment.search_filter:
        class: App\Swagger\Filter\SwaggerSearchFilter
        decorates: 'app.comment.search_filter'
        arguments: [ '@app.swagger.comment.search_filter.inner' ]

    app.swagger.comment.group_filter:
        class: App\Swagger\Filter\SwaggerGroupFilter
        decorates: 'app.comment.group_filter'
        arguments: [ '@app.swagger.comment.group_filter.inner' ]

    app.swagger.comment_reply.search_filter:
        class: App\Swagger\Filter\SwaggerSearchFilter
        decorates: 'app.comment_reply.search_filter'
        arguments: [ '@app.swagger.comment_reply.search_filter.inner' ]