api_platform:
    # The title of the API.
    title: '%env(APP_TITLE)%'

    # The description of the API.
    description: '%env(APP_DESCRIPTION)%'

    # The version of the API.
    version: '%env(APP_VERSION)%'

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    # Enable the FOSUserBundle integration.
    enable_fos_user: true

    # The list of enabled formats. The first one will be the default.
    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']
        xml:
            mime_types: ['application/xml', 'text/xml']
        html:
            mime_types: ['text/html']

    # Enable the Swagger documentation and export.
    enable_swagger: true

    # Enable Swagger ui.
    enable_swagger_ui: true

    collection:
        # The default order of results.
        order: 'ASC'

        # The name of the query parameter to order results.
        order_parameter_name: 'order'

        pagination:
            client_items_per_page: true
            items_per_page_parameter_name: limit

    http_cache:
        # Automatically generate etags for API responses.
        etag: true

        # Default value for the response max age.
        max_age: 0

        # Default value for the response shared (proxy) max age.
        shared_max_age: 3600

        # Default values of the "Vary" HTTP header.
        vary: ['Content-Type', 'Authorization']

        # To make all responses public by default.
        public: true

        invalidation:
            # To enable the tags-based cache invalidation system.
            enabled: false

            # URLs of the Varnish servers to purge using cache tags when a resource is updated.
            varnish_urls: ['']