easy_admin:
    list:
        actions: ['show', 'edit', 'delete']
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - fullname
                    - username
                    - email
                    - enabled
            form:
                fields:
                    - fullname
                    - username
                    - email
                    - enabled
                    - lastLogin
                    - { property: plainPassword,
                        type: 'text',
                        type_options: {
                            required: false
                        } }

                    - { property: roles,
                        type: 'choice',
                        type_options: {
                            multiple: true,
                            choices: {
                                USER: 'ROLE_USER',
                                READER: 'ROLE_READER',
                                ADMIN: 'ROLE_ADMIN',
                                SUPER_ADMIN: 'ROLE_SUPER_ADMIN',
                            } } }

        Project:
            class: App\Entity\Project
            list:
                fields:
                    - name
                    - { property: 'author', type_options: { by_reference: false } }
                    - url
                    - createdAt
            form:
                fields:
                    - name
                    - description
                    - url
                    - { property: 'author', type_options: { by_reference: true } }
