nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:[0-9]+']
        allow_headers: ['Content-type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: ['link']
        max_age: 0
        hosts: []
        origin_regex: true
        forced_allow_origin_value: ~
    paths:
        '^/': ~