nelmio_cors:
    defaults:
        origin_regex: true
        allow_credentials: false
        allow_origin: ['http://knit.pk.edu.pl']
        allow_headers: ['Accept', 'Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: ['Link']
        max_age: 3600
        hosts: []
        forced_allow_origin_value: ~
    paths:
        '^/': ~