security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_READER: ROLE_USER
        ROLE_ADMIN: [ROLE_READER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        in_memory: { memory: ~ }
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:

        admin_login:
            pattern: ^/admin/login$
            anonymous: true

        admin:
            pattern:  ^/admin
            stateless: false
            anonymous: false
            provider: fos_userbundle
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: true
                default_target_path: /admin

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /admin

            logout:
                path: fos_user_security_logout
                target: fos_user_security_login

        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: fos_userbundle
            json_login:
                check_path: api_login_check
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        v1:
            pattern: ^/v1/\w+
            provider: fos_userbundle
            anonymous: false
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix: Bearer
#               query_parameter:
#                   enabled: true
#                   name: token
                throw_exceptions: false
                create_entry_point: true

        main:
            pattern:   ^/
            anonymous: true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/v1/\w+, roles: ROLE_READER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
