security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_USER: [ROLE_READER]
        ROLE_WRITER: [ROLE_USER]
        ROLE_ADMIN: [ROLE_WRITER, ROLE_USER_WRITER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        in_memory: { memory: ~ }
        jwt:
            lexik_jwt:
                class: App\Security\User\JWTUser
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        token:
            pattern: ^/token
            stateless: true
            anonymous: true
            provider: fos_userbundle
            json_login:
                check_path: api_login_check
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/
            stateless: true
            anonymous: true
            provider: jwt
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
