vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        images:
            uri_prefix: '/%public_upload.prefix%'
            namer: vich_uploader.namer_uniqid
            upload_destination: images_filesystem_prefix
