vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: '/%env(PUBLIC_UPLOAD_PREFIX)%'
            namer: vich_uploader.namer_uniqid
            upload_destination: '%kernel.project_dir%/public/%env(PUBLIC_UPLOAD_PREFIX)%'
