language: php
sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - APP_ENV=test

matrix:
  include:
    - php: '7.2'
      services:
        - mysql
      addons:
        apt:
          sources:
            - mysql-5.7-trusty
          packages:
            - mysql-server
      before_script:
        - mysql -e 'CREATE DATABASE knit_api_test;'
      env:
        - DATABASE_URL="mysql://travis@127.0.0.1:3306/knit_api_test?charset=utf8mb4&serverVersion=5.7"
    - php: '7.2'
      services:
        - postgresql
      before_script:
        - psql -c 'CREATE DATABASE knit_api_test;' -U postgres
      env:
        - DATABASE_URL="pgsql://postgres@127.0.0.1:5432/knit_api_test"
    - php: '7.2'

before_install:
  - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
  - composer update --prefer-dist --no-progress --no-suggest --no-scripts --ansi;

script:
  - composer test
  - if [[ -v DATABASE_URL ]]; then bin/console doctrine:schema:create; fi
  - if [[ -v DATABASE_URL ]]; then bin/console doctrine:fixtures:load -n; fi
  - if [[ -v DATABASE_URL ]]; then composer test-features -n; fi
