version: "3"

volumes:
  mysql_data:

services:
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=database
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        volumes:
            - mysql_data:/var/lib/mysql

    oracle:
        image: k911/oracle-12c:0.0.1
        ports:
            - "1521:1521"
            - "5500:5500"

    redis:
        build:
            context: ./docker/redis
        environment:
            - REDIS_PASSWORD=redis
        ports:
            - "6379:6379"

    # PHP Application running on PHP-FPM (MySQL)
#    backend:
#        depends_on:
#            - db
#            - redis
#        build:
#            context: ./docker/php
#            dockerfile: Dockerfile.mysql
#        environment:
#            - APP_VAR_PATH=/var/app
#            - DOT_ENV=.env.dist
#        volumes:
#            - .:/var/www/app
#            - ./logs/app:/var/app/log
#            - ./logs/php:/var/log/php
#            - ./logs/supervisor:/var/log/supervisor

    backend:
        depends_on:
            - oracle
            - redis
        build:
            context: ./docker/php
            dockerfile: Dockerfile.oci
        environment:
            - APP_VAR_PATH=/var/app
            - DOT_ENV=.env.oci
        volumes:
            - .:/var/www/app
            - ./logs/app:/var/app/log
            - ./logs/php:/var/log/php
            - ./logs/supervisor:/var/log/supervisor

    # Nginx
    api:
        depends_on:
            - backend
        build:
            context: ./docker/api
        ports:
            - "8080:80"
        volumes:
            - ./logs/nginx:/var/log/nginx
            - ./public:/var/www/app/public
            - ./vendor:/var/www/app/vendor

    ## Debug/DevOps

    # Varnish (Http Cache)
    cache:
        depends_on:
            - api
        build:
            context: ./docker/cache
        ports:
            - "80:80"

#    elasticsearch:
#        build:
#            context: docker/elasticsearch
#        ports:
#            - "9200:9200"
#
#    logstash:
#        build:
#            context: docker/logstash
#        environment:
#            - xpack.monitoring.enabled=false
#        ports:
#            - "9600:9600"
#        depends_on:
#            - redis
#            - elasticsearch
#
#    kibana:
#        build:
#            context: docker/kibana
#        environment:
#            - xpack.monitoring.enabled=false
#        depends_on:
#            - elasticsearch
#        ports:
#            - "5601:5601"

#    pma:
#        build:
#            context: ./docker/pma
#        depends_on:
#            - db
#        environment:
#            - PMA_HOST=db
#            - PMA_USER=user
#            - PMA_PASSWORD=password
#        ports:
#            - "8000:80"