version: "3"

volumes:
    mysql_data:

services:
    mysql:
        image: mysql:5.7
        ports:
           - "3306:3306"
        environment:
           - MYSQL_RANDOM_ROOT_PASSWORD=yes
           - MYSQL_DATABASE=database
           - MYSQL_USER=user
           - MYSQL_PASSWORD=password
        volumes:
           - mysql_data:/var/lib/mysql

    redis:
        build:
            context: ./docker/redis
        environment:
            - REDIS_PASSWORD=redis
        ports:
            - "6379:6379"

    # PHP Application running on PHP-FPM (MySQL)
    backend:
        depends_on:
            - mysql
            - redis
        build: .
        environment:
#         - DOT_ENV=.env.mysql
          - APP_ENV=prod
          - APP_SECRET=a17636f12ff5ffc0c4f03a98d088e74adba75e55
          - DATABASE_URL="mysql://user:password@mysql:3306/database?charset=utf8mb4&serverVersion=5.7"
          - JWT_PRIVATE_KEY_PATH=config/jwt/private.pem
          - JWT_PUBLIC_KEY_PATH=config/jwt/public.pem
          - JWT_PASSPHRASE=56c247d4c281f5de0d8d9d894f2b605157fd379c
          - APP_TRUSTED_HOSTS=['localhost','api','varnish']
          - APP_TRUSTED_PROXIES=['10.0.0.0/8','172.16.0.0/12','192.168.0.0/16']
          - REDIS_URI=redis://:redis@redis:6379
          - VARNISH_URL=http://varnish
        volumes:
            - .:/usr/src/api
            - /usr/src/api/var

    ppm:
        depends_on:
            - mysql
            - redis
        image: phppm/nginx
        command: --debug=1 -vv --app-env=dev --static-directory=public/
        volumes:
            - .:/var/www
        ports:
            - "8090:80"

    # Nginx
    api:
        depends_on:
            - backend
        build:
            context: ./docker/api
        ports:
            - "8080:80"
        volumes:
            - ./public:/usr/src/api/public
            - ./vendor:/usr/src/api/vendor

    ## Debug/DevOps

    # Varnish (Http Cache)
    varnish:
        depends_on:
           - api
        build:
           context: ./docker/varnish
        volumes:
            - ./docker/varnish/conf:/etc/varnish:ro
        ports:
           - "80:80"

#    elasticsearch:
#        build:
#            context: docker/elasticsearch
#        ports:
#            - "9200:9200"
#
#    logstash:
#        build:
#            context: docker/logstash
#        environment:
#            - xpack.monitoring.enabled=false
#        ports:
#            - "9600:9600"
#        depends_on:
#            - redis
#            - elasticsearch
#
#    kibana:
#        build:
#            context: docker/kibana
#        environment:
#            - xpack.monitoring.enabled=false
#        depends_on:
#            - elasticsearch
#        ports:
#            - "5601:5601"

    pma:
        build:
            context: ./docker/pma
        depends_on:
            - mysql
        environment:
            - PMA_HOST=mysql
            - PMA_USER=user
            - PMA_PASSWORD=password
        ports:
            - "8000:80"
