version: "3"
volumes:
  app_var:

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  php:
    build:
      context: ./docker/php-fpm-alpine
    volumes:
      - .:/var/www/app
      - ./logs/app:/var/www/app/var/logs
      - ./logs/php:/var/log/php
      - ./logs/supervisor:/var/log/supervisor
      - app_var:/var/www/app/var

  nginx:
    build:
      context: ./docker/nginx-alpine
    ports:
      - "80:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./public:/var/www/app/public
      - ./vendor:/var/www/app/vendor

#  elk:
#    build: ./docker/elk
#    ports:
#      - "8080:80"
#    volumes:
#      - ./docker/elk/logstash:/etc/logstash
#      - ./docker/elk/logstash/patterns:/opt/logstash/patterns
#      - ./logs:/var/log

  pma:
    build: docker/pma
    environment:
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - "37680:80"