services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    'App\Bundle\SwooleBundle\Server\AtomicCounter':
        factory: [App\Bundle\SwooleBundle\Server\AtomicCounter, fromZero]

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\HttpFoundationRequestFactoryInterface':
        class: App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\HttpFoundationRequestFactory

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\CloudFrontHttpFoundationRequestFactory':
        decorates: App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\HttpFoundationRequestFactoryInterface
        decoration_priority: -10
        arguments: ['@App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\CloudFrontHttpFoundationRequestFactory.inner']
        autoconfigure: false

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\HttpFoundationResponseHandlerInterface':
        class: App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\HttpFoundationResponseHandler

    'App\Bundle\SwooleBundle\Driver\DriverInterface':
        class: App\Bundle\SwooleBundle\Bridge\Symfony\HttpKernel\HttpKernelDriver

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpKernel\TrustAllProxiesHttpKernelDriver':
        decorates: App\Bundle\SwooleBundle\Driver\DriverInterface
        decoration_priority: -10
        arguments: ['@App\Bundle\SwooleBundle\Bridge\Symfony\HttpKernel\TrustAllProxiesHttpKernelDriver.inner']
        autoconfigure: false

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpKernel\DebugHttpKernelDriver':
        decorates: App\Bundle\SwooleBundle\Driver\DriverInterface
        decoration_priority: -20
        arguments: ['@App\Bundle\SwooleBundle\Bridge\Symfony\HttpKernel\DebugHttpKernelDriver.inner']
        autoconfigure: false

    'Swoole\Http\Server':

    'App\Bundle\SwooleBundle\Command\ServerRunCommand':
        tags: ['console.command']
    'App\Bundle\SwooleBundle\Command\ServerProfileCommand':
        tags: ['console.command']
