services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    swoole.counter.atomic:
        class: App\Bundle\SwooleBundle\Server\AtomicCounter
        factory: [App\Bundle\SwooleBundle\Server\AtomicCounter, fromZero]

    swoole.server.http:
        class: Swoole\Http\Server

    swoole.server.run_command:
        class: App\Bundle\SwooleBundle\Command\ServerRunCommand
        arguments:
            $server: '@swoole.server.http'
        tags: ['console.command']

    swoole.server.profile_command:
        class: App\Bundle\SwooleBundle\Command\ServerProfileCommand
        arguments:
            $counter: '@swoole.counter.atomic'
            $server: '@swoole.server.http'
        tags: ['console.command']
