easy_admin:
    list:
        actions: ['show', 'edit', 'delete']
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - fullname
                    - username
                    - email
                    - enabled
            form:
                fields:
                    - fullname
                    - username
                    - email
                    - enabled
                    - lastLogin
                    - { property: plainPassword,
                        type: 'text',
                        type_options: {
                            required: false
                        } }

                    - { property: roles,
                        type: 'choice',
                        type_options: {
                            multiple: true,
                            choices: {
                                USER: 'ROLE_USER',
                                READER: 'ROLE_READER',
                                WRITER: 'ROLE_WRITER',
                                ADMIN: 'ROLE_ADMIN',
                                SUPER_ADMIN: 'ROLE_SUPER_ADMIN',
                            } } }

        Project:
            class: App\Entity\Project
            list:
                fields:
                    - name
                    - author
                    - url
                    - createdAt
            form:
                fields:
                    - name
                    - description
                    - url
                    - author
        Article:
            class: App\Entity\Article
            list:
                fields:
                    - title
                    - category
                    - author
                    - createdAt
                    - tags
                    - published
            form:
                fields:
                    - title
                    - category
                    - description
                    - content
                    - tags
                    - author
            edit:
                fields:
                    - published
        Tag:
            class: App\Entity\Tag
            list:
                fields:
                    - name
                    - code
            form:
                fields:
                    - name
        Category:
            class: App\Entity\Category
            list:
                fields:
                    - name
                    - code
            form:
                fields:
                    - name