easy_admin:
    list:
        actions: ['show', 'edit', 'delete']
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - fullname
                    - username
                    - email
                    - securityRoles
                    - enabled
                    - superAdmin
            form:
                fields:
                    - fullname
                    - username
                    - email
                    - enabled
                    - superAdmin
                    - lastLogin
                    - securityRoles
                    - { property: plainPassword,
                        type: 'text',
                        type_options: {
                            required: false
                        } }

        Project:
            class: App\Entity\Project
            list:
                fields:
                    - name
                    - author
                    - url
                    - createdAt
            form:
                fields:
                    - name
                    - description
                    - url
                    - author
        Article:
            class: App\Entity\Article
            list:
                fields:
                    - title
                    - category
                    - author
                    - createdAt
                    - tags
                    - published
            form:
                fields:
                    - title
                    - category
                    - description
                    - content
                    - tags
                    - author
            edit:
                fields:
                    - published
        Tag:
            class: App\Entity\Tag
            list:
                fields:
                    - name
                    - code
            form:
                fields:
                    - name
        Category:
            class: App\Entity\Category
            list:
                fields:
                    - name
                    - code
            form:
                fields:
                    - name
        SecurityRole:
            class: App\Entity\SecurityRole
            list:
                fields:
                    - id
                    - role
                    - users
            form:
                fields:
                    - role
                    - { property: 'users', type_options: { by_reference: false } }