nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:[0-9]+', 'https://knit-test-homepage.tk', 'https://knit-stage-homepage.herokuapp.com', 'https://d15e2ckuuchn46.cloudfront.net', 'http://knit-stage-api.eu-central-1.elasticbeanstalk.com']
