api_action:
    resource: ../src/Action/
    type: annotation

api_login_check:
    path: /token
    methods: ['POST']

article_add_comment:
    path: '/articles/{id}/comments'
    methods: ['POST']
    defaults:
        _controller: App\Action\Thought\AddThoughtAction
        _api_collection_operation_name: article_add_comment
        _api_parent_context:
            item_operation_name: api_articles_get_item
            resource_class: App\Entity\Article
        _api_resource_class: App\Entity\Comment

comment_add_comment_reply:
    path: '/comments/{id}/comment_replies'
    methods: ['POST']
    defaults:
        _controller: App\Action\Thought\AddThoughtAction
        _api_collection_operation_name: comment_add_comment_reply
        _api_parent_context:
            item_operation_name: api_comments_get_item
            resource_class: App\Entity\Comment
        _api_resource_class: App\Entity\CommentReply
