services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    ### Redis client
    redis.client:
        class: Predis\Client
        arguments:
            - '%env(REDIS_URI)%'

    ### Monolog set-up for elastic stack
    monolog.formatter.logstash_formatter:
        class: Monolog\Formatter\LogstashFormatter
        arguments:
            - 'api' # 'type' field in kibana

    monolog.handler.redis_handler:
        class: Monolog\Handler\RedisHandler
        arguments:
            - '@redis.client'
            - 'monolog' # under this key, logs will be stored in redis
            - 'info'
        calls:
            - [ setFormatter, ['@monolog.formatter.logstash_formatter']]
    database.oracle.listener:
        class: Doctrine\DBAL\Event\Listeners\OracleSessionInit
        tags:
            - { name: doctrine.event_listener, event: postConnect, connection: default }
